#端口默认为md5(us.haojiankang.com)<<48>>48
server:
  port: 4437
  url: http://127.0.0.1:${server.port}
spring:
  datasource:
    url: jdbc:sqlite:%s%sus.db
    classname: org.sqlite.JDBC
logging:
  level:
     com:
        haojiankang:
           aum:
              daemon: debug
aum:
  daemon:
      version: 1.0.0
      name: aum-daemon
      appcode: aum-daemon
      startup: sc start aum-daemon
      shutdown: sc stop aum-daemon
      exec: cmd /c start cmd /c "java -jar %s update %s >> %supgrade.log"